sonar.projectKey=user-service
sonar.projectName=User Service
sonar.sources=src/main/java
sonar.host.url=http://127.0.0.1:49160
sonar.token=sqp_4361b4f84f243ac36b0a060a8dc89f937705b0e6
sonar.java.binaries=target/classes
