pipeline {

    agent any

    environment {

        IMAGE_NAME = 'maitrelpg/user-service'

        IMAGE_TAG = "${BUILD_NUMBER}"

    }

    stages {

        stage('Checkout Code') {

            steps {

                deleteDir()

                checkout scm

            }

        }

        stage('Build JAR') {

            steps {

                dir('ensitech-spring-microservice/user-service') {

                    sh 'chmod +x ../mvnw'

                    sh '../mvnw clean package -DskipTests'

                }

            }

        }

        stage('Run Tests') {

            steps {

                dir('ensitech-spring-microservice/user-service') {

                    sh '../mvnw test'

                }

            }

        }

        stage('SonarQube Analysis') {

            steps {

                dir('ensitech-spring-microservice/user-service') {

                    withSonarQubeEnv('sonarqube-server') {

                        sh '../mvnw sonar:sonar -Dsonar.projectKey=user-service -Dsonar.projectName=user-service -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_AUTH_TOKEN'

                    }

                }

            }

        }

        stage('Build Docker Image') {

            steps {

                dir('ensitech-spring-microservice/user-service') {

                    sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG .'

                    sh 'docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest'

                }

            }

        }

        stage('Login to Docker Hub') {

            steps {

                withCredentials([usernamePassword(

                    credentialsId: 'dockerhub-credentials',

                    usernameVariable: 'DOCKERHUB_USERNAME',

                    passwordVariable: 'DOCKERHUB_PASSWORD'

                )]) {

                    sh 'echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin'

                }

            }

        }

        stage('Push Docker Image') {

            steps {

                sh 'docker push $IMAGE_NAME:$IMAGE_TAG'

                sh 'docker push $IMAGE_NAME:latest'

            }

        }

    }

    post {

        always {

            archiveArtifacts artifacts: 'ensitech-spring-microservice/user-service/target/*.jar', fingerprint: true

            cleanWs()

        }

        success {

            echo 'Backend pipeline completed successfully.'

        }

        failure {

            echo 'Backend pipeline failed.'

        }

    }

}