apiVersion: apps/v1

kind: Deployment

metadata:

  name: academic-service

spec:

  replicas: 1

  selector:

    matchLabels:

      app: academic-service

  template:

    metadata:

      labels:

        app: academic-service

    spec:

      containers:

        - name: academic-service

          image: maitrelpg/academic-service:latest

          ports:

            - containerPort: 8085